name: REDREVLIFE
favicon: null
layout_spectrum: 0.9915526837576181
typography_spectrum: 0.7456269497051835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#241a19'
    - '#f8f8f8'
    - '#006ea9'
    - '#9abbce'
    - '#474c60'
  brandStrength: 0.9375
  lightness: 0.6203158181160688
  saturation: 0.5134810884483159
  rhythmicContrast: 0.09805723815225065
purpose: []
